version: "3"

services:
  mongo:
    image: mongo

  redis:
    image: redis

  app_test:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth_server
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis
    command:
      yarn run test
